### ISSUE TITLE
reload() was moved to importlib in Python 3

### ISSUE THREAD

**Issue by cclauss** [brightmart/text_classification#8]
As discussed in #6, [these four lines](https://github.com/brightmart/text_classification/blob/master/a01_FastText/p5_fastTextB_predict.py#L4-L7) (or something similar) need to be added to the following files for them to work in Python 3.

```
./a8_predict.py:5:1: F821 undefined name 'reload'
./a8_train.py:5:1: F821 undefined name 'reload'
./a01_FastText/p5_fastTextB_predict.py:5:1: F821 undefined name 'reload'
./a01_FastText/p5_fastTextB_predict_multilabel.py:5:1: F821 undefined name 'reload'
./a01_FastText/p5_fastTextB_train.py:5:1: F821 undefined name 'reload'
./a02_TextCNN/p7_TextCNN_predict.py:5:1: F821 undefined name 'reload'
./a02_TextCNN/p7_TextCNN_train.py:5:1: F821 undefined name 'reload'
./a02_TextCNN/other_experiement/p7_TextCNN_predict_exp.py:5:1: F821 undefined name 'reload'
./a02_TextCNN/other_experiement/p7_TextCNN_predict_exp512.py:5:1: F821 undefined name 'reload'
./a02_TextCNN/other_experiement/p7_TextCNN_predict_exp512_0609.py:5:1: F821 undefined name 'reload'
./a02_TextCNN/other_experiement/p7_TextCNN_predict_exp512_simple.py:5:1: F821 undefined name 'reload'
./a02_TextCNN/other_experiement/p7_TextCNN_train_exp.py:5:1: F821 undefined name 'reload'
./a02_TextCNN/other_experiement/p7_TextCNN_train_exp512.py:5:1: F821 undefined name 'reload'
./a02_TextCNN/other_experiement/p7_TextCNN_train_exp_512_0609.py:5:1: F821 undefined name 'reload'
./a02_TextCNN/other_experiement/p8_TextCNN_predict_exp.py:5:1: F821 undefined name 'reload'
./a03_TextRNN/p8_TextRNN_predict.py:5:1: F821 undefined name 'reload'
./a03_TextRNN/p8_TextRNN_train.py:5:1: F821 undefined name 'reload'
./a04_TextRCNN/p71_TextRCNN_predict.py:5:1: F821 undefined name 'reload'
./a04_TextRCNN/p71_TextRCNN_train.py:5:1: F821 undefined name 'reload'
./a05_HierarchicalAttentionNetwork/p1_HierarchicalAttention_predict.py:5:1: F821 undefined name 'reload'
./a05_HierarchicalAttentionNetwork/p1_HierarchicalAttention_train.py:5:1: F821 undefined name 'reload'
./a06_Seq2seqWithAttention/a1_seq2seq_attention_predict.py:5:1: F821 undefined name 'reload'
./a06_Seq2seqWithAttention/a1_seq2seq_attention_train.py:5:1: F821 undefined name 'reload'
./a07_Transformer/a2_predict.py:5:1: F821 undefined name 'reload'
./a07_Transformer/a2_train.py:5:1: F821 undefined name 'reload'
./a08_EntityNetwork/a3_predict.py:5:1: F821 undefined name 'reload'
./a08_EntityNetwork/a3_train.py:5:1: F821 undefined name 'reload'
./aa1_data_util/2_predict_zhihu_get_question_representation.py:3:1: F821 undefined name 'reload'
./aa1_data_util/3_process_zhihu_question_topic_relation.py:3:1: F821 undefined name 'reload'
./aa4_TextCNN_with_RCNN/p72_TextCNN_with_RCNN_train.py:5:1: F821 undefined name 'reload'
./aa5_BiLstmTextRelation/p9_BiLstmTextRelation_train.py:5:1: F821 undefined name 'reload'
./aa6_TwoCNNTextRelation/p9_twoCNNTextRelation_train.py:5:1: F821 undefined name 'reload'
```

**Comment by brightmart** [comment]
this is solved. right?

**Comment by cclauss** [comment]
No, it is not fixed.  I solved the issue in one file to show how it is done.  However all these other files have not yet been fixed.

**Comment by brightmart** [comment]
i see. will add it to all soon.
